ARTIST_EN = {
"坂本龍一（2017年ゲストディレクター）":"Ryuichi Sakamoto (Guest Director, 2017)",
"大友良英":"Yoshihide Otomo",
"クリスチャン・マークレー":"Christian Marclay",
"毛利悠子":"Yuko Mohri",
"草間彌生":"Yayoi Kusama",
"奈良美智":"Yoshitomo Nara",
"ロン・ミュエク":"Ron Mueck",
"エルヴィン・ヴルム":"Erwin Wurm",
"鹿踊り・虎舞・神楽などの郷土芸能団体":"Local performing-arts groups including shishi-odori, toramai, and kagura",
"アジア各地の芸能・ダンスグループ":"Performing-arts and dance groups from across Asia",
"小林武史":"Takeshi Kobayashi",
"川俣正":"Tadashi Kawamata",
"伊勢谷友介":"Yusuke Iseya",
"加藤泉":"Izumi Kato",
"尾花賢一":"Kenichi Obana",
"迎英里子":"Eriko Mukai",
"永沢碧衣":"Aoi Nagasawa",
"秋田公立美術大学の学生作家":"Student artists from Akita University of Art",
"稲葉俊郎（芸術監督）":"Toshiro Inaba (Artistic Director)",
"大和由佳":"Yuka Yamato",
"山本桂輔":"Keisuke Yamamoto",
"タル・ベーラ（映画監督）":"Béla Tarr (Film Director)",
"古川日出男":"Hideo Furukawa",
"大森克己":"Katsumi Omori",
"藤浩志":"Hiroshi Fuji",
"アヴニー・タンドゥン・ヴィエラ":"Avani Tandon Vieira",
"イブラヒム・クルト":"İbrahim Kurt",
"佐藤浩一":"Koichi Sato",
"日野皓正":"Terumasa Hino",
"山下洋輔（取手ジャズフェスティバル出演）":"Yosuke Yamashita (Toride Jazz Festival performer)",
"田原唯之":"Tadayuki Tahara",
"髙山瑞":"Midori Takayama",
"船山哲郎":"Tetsuro Funayama",
"木村剛士":"Tsuyoshi Kimura",
"浅野暢晴":"Nobuharu Asano",
"アニタ・ガラツツァ":"Anita Gratzer",
"山形敦子":"Atsuko Yamagata",
"中村政人（総合ディレクター）":"Masato Nakamura (General Director)",
"加藤翼":"Tsubasa Kato",
"高嶺格":"Tadasu Takamine",
"鈴木昭男":"Akio Suzuki",
"栗原良彰":"Yoshiaki Kurihara",
"黒川岳":"Gaku Kurokawa",
"森靖":"Yasushi Mori",
"志村茉那美":"Manami Shimura",
"照沼敦朗":"Atsuro Terunuma",
"トモトシ":"Tomotoshi",
"増山士郎":"Shiro Masuyama",
"イリヤ＆エミリア・カバコフ":"Ilya & Emilia Kabakov",
"塩田千春":"Chiharu Shiota",
"田中泯":"Min Tanaka",
"クリスチャン・ボルタンスキー":"Christian Boltanski",
"アントニー・ゴームリー":"Antony Gormley",
"デイル・チフーリ（美術館シンボル作品）":"Dale Chihuly (museum signature installation)",
"小島有香子":"Yukako Kojima",
"秋元雄史（アーティスティックディレクター）":"Yuji Akimoto (Artistic Director)",
"国内外の工芸・現代アート作家約30組":"Around 30 craft and contemporary-art artists/groups from Japan and abroad",
"カミラ・スヴェンソン（ブラジル）":"Camila Svenson (Brazil)",
"公募で選出される国内外のアーティスト":"Artists from Japan and abroad selected through an open call",
"南條史生（アート展ディレクター）":"Fumio Nanjo (Art Exhibition Director)",
"大巻伸嗣":"Shinji Ohmaki",
"落合陽一":"Yoichi Ochiai",
"清川あさみ":"Asami Kiyokawa",
"A-POC ABLE ISSEY MIYAKE":"A-POC ABLE ISSEY MIYAKE",
"北川フラム（総合ディレクター）":"Fram Kitagawa (General Director)",
"鈴木理策":"Risaku Suzuki",
"淺井裕介":"Yusuke Asai",
"皆川明（ビジュアルディレクター）":"Akira Minagawa (Visual Director)",
"石井幹子（照明デザイナー・特別顧問）":"Motoko Ishii (Lighting Designer / Special Advisor)",
"堀木エリ子（和紙アートディレクター）":"Eriko Horiki (Washi Art Director)",
"宮城聰（SPAC芸術総監督）":"Satoshi Miyagi (SPAC General Artistic Director)",
"鈴木忠志（初代芸術総監督）":"Tadashi Suzuki (Founding General Artistic Director)",
"ヤノベケンジ":"Kenji Yanobe",
"ウーゴ・ロンディノーネ":"Ugo Rondinone",
"ムルヤナ":"Mulyana",
"浅野言朗":"Kotaro Asano",
"ティモ・ライト（フィンランド）":"Timo Wright (Finland)",
"中田洋子（総合ディレクター）":"Yoko Nakata (General Director)",
"ガブリエラ・モラウェッツ":"Gabriela Morawetz",
"青木美歌":"Mika Aoki",
"森山大道":"Daido Moriyama",
"アントン・コービン":"Anton Corbijn",
"イヴ・マルシャン＆ロマン・メフル":"Yves Marchand & Romain Meffre",
"アーネスト・コール":"Ernest Cole",
"コンタクト・ゴンゾ（塚原悠也・垣尾優）":"contact Gonzo (Yuya Tsukahara / Masaru Kakio)",
"名村造船所跡拠点のアーティスト群":"Artists based at the former Namura Shipbuilding site",
"林勇気（映像作家）":"Yuki Hayashi (Video Artist)",
"to R mansion":"to R mansion",
"神戸・新開地ゆかりの若手アーティスト":"Emerging artists connected to Kobe and Shinkaichi",
"坂野真子":"Mako Sakano",
"藤田千代":"Chiyo Fujita",
"六車紀子":"Noriko Muguruma",
"おとたまり（岩田茉莉江）":"Ototamari (Marie Iwata)",
"Dragon76":"Dragon76",
"YOSHI47":"YOSHI47",
"Jack Soren":"Jack Soren",
"石塚大介":"Daisuke Ishizuka",
"森村泰昌":"Yasumasa Morimura",
"やなぎみわ":"Miwa Yanagi",
"伊藤若冲・アンディ・ウォーホル・ゲルハルト・リヒター（開館記念展）":"Jakuchu Ito / Andy Warhol / Gerhard Richter (opening exhibition)",
"竹内大樹（発起人・舞台俳優）":"Daiki Takeuchi (Founder / Stage Actor)",
"加藤泉（石見美術館ゆかりの国際的作家）":"Izumi Kato (international artist associated with Iwami Art Museum)",
"リクリット・ティラヴァーニャ（2022年アーティスティックディレクター）":"Rirkrit Tiravanija (Artistic Director, 2022)",
"片山真理":"Mari Katayama",
"ダン・グラハム":"Dan Graham",
"ピエール・ユイグ":"Pierre Huyghe",
"安藤忠雄":"Tadao Ando",
"伊東豊雄":"Toyo Ito",
"妹島和世・西沢立衛（SANAA）":"Kazuyo Sejima & Ryue Nishizawa (SANAA)",
"丹下健三":"Kenzo Tange",
"坂本龍一":"Ryuichi Sakamoto",
"高谷史郎":"Shiro Takatani",
"池田亮司":"Ryoji Ikeda",
"金子未弥":"Miya Kaneko",
"Iede Reckman":"Iede Reckman",
"Shirley Cho":"Shirley Cho",
"横尾忠則":"Tadanori Yokoo",
"内藤礼":"Rei Naito",
"西沢立衛":"Ryue Nishizawa",
"ジュリアン・オピー":"Julian Opie",
"大竹伸朗":"Shinro Ohtake",
"蜷川実花":"Mika Ninagawa",
"エマニュエル・ムホー":"Emmanuelle Moureaux",
"石川直樹":"Naoki Ishikawa",
"石元泰博（高知県立美術館収蔵作家）":"Yasuhiro Ishimoto (artist represented in the museum collection)",
"マルク・シャガール（同館収蔵作品）":"Marc Chagall (works in the museum collection)",
"KYNE":"KYNE",
"村上信理":"Shinri Murakami",
"生島国宜":"Kuniyoshi Ikushima",
"ミレナ・アンナ・バウマ":"Milena Anna Bauma",
"マルー・ブリュー":"Malou Brieux",
"ベネデッタ・ポムピリ":"Benedetta Pompili",
"今泉奏":"Kanade Imaizumi",
"公募で選出される国内外の版画作家":"Printmakers from Japan and abroad selected through an open call",
"磯崎新（初代コミッショナー）":"Arata Isozaki (Founding Commissioner)",
"伊東豊雄（3代目コミッショナー）":"Toyo Ito (3rd Commissioner)",
"篠原一男":"Kazuo Shinohara",
"マイケル・リン":"Michael Lin",
"アデル・アブデスメッド":"Adel Abdessemed",
"中山晃子":"Akiko Nakayama",
"リム・ソクチャンリナ":"Lim Sokchanlina",
"武田双雲":"Souun Takeda",
"緒方智奈美":"Chinami Ogata",
"安積一仁":"Kazuhito Azumi",
"ダニ・カラバン":"Dani Karavan",
"ジョナサン・ボロフスキー":"Jonathan Borofsky",
"Chim↑Pom from Smappa!Group":"Chim↑Pom from Smappa!Group",
"椿昇":"Noboru Tsubaki",
"淀川テクニック":"Yodogawa Technique",
"小森はるか":"Haruka Komori",
"大木裕之":"Hiroyuki Oki",
"侯怡亭（台湾）":"Hou I-Ting (Taiwan)",
"旧岩崎邸庭園（ジョサイア・コンドル）":"Kyu-Iwasaki-tei Gardens (Josiah Conder)",
"三菱一号館":"Mitsubishi Ichigokan Museum",
"GINZA SIX":"GINZA SIX",
"慶應義塾大学図書館旧館":"Keio University Old Library",
"山口藍":"Ai Yamaguchi",
"蔵真墨":"Masumi Kura",
"岡田裕子":"Hiroko Okada",
"山崎広太":"Kota Yamazaki",
"イケムラレイコ":"Leiko Ikemura",
"潘逸舟":"Han Ishu",
"渋谷慶一郎":"Keiichiro Shibuya",
"アレクサ・クミコ・ハタナカ":"Alexa Kumiko Hatanaka",
"マルタン・マルジェラ":"Martin Margiela",
"遠藤利克":"Toshikatsu Endo",
"バルトロメイ・トグオ":"Barthélémy Toguo",
"スタシス・エイドリゲヴィチウス":"Stasys Eidrigevičius",
"マッシモ・バルトリーニ":"Massimo Bartolini",
"EAT & ART TARO":"EAT & ART TARO",
"橘葉月":"Hazuki Tachibana",
"牛島光太郎":"Koutarou Ushijima",
"ユミソン（総合ディレクター）":"Yumi Song (General Director)",
"SIDE CORE":"SIDE CORE",
"飯山由貴":"Yuki Iiyama",
"KIGI（植原亮輔・渡邉良重）":"KIGI (Ryosuke Uehara / Yoshie Watanabe)",
"宮永愛子":"Aiko Miyanaga",
"髙橋匡太":"Kyota Takahashi",
"チームラボ":"teamLab",
"小松美羽":"Miwa Komatsu",
"小林武史（総合プロデューサー）":"Takeshi Kobayashi (General Producer)",
"豊福亮（アートディレクター）":"Ryo Toyofuku (Art Director)",
"サンドラ・ムジンガ":"Sandra Mujinga",
"ピッパ・ガーナー":"Pippa Garner",
"ニック・ケイヴ":"Nick Cave",
"アイ・ウェイウェイ":"Ai Weiwei",
"ヨアル・ナンゴ":"Joar Nango",
"フランシス真悟":"Shingo Francis",
"Ahmet ÖZEL（トルコ）":"Ahmet Özel (Turkey)",
"Anka KRASNA（スロベニア）":"Anka Krasna (Slovenia)",
"加賀谷武":"Takeshi Kagaya",
"佐久間宣行（アンバサダー）":"Nobuyuki Sakuma (Ambassador)",
"ダウ90000":"Daw 90000",
"河口龍夫（筑波大学名誉教授）":"Tatsuo Kawaguchi (Professor Emeritus, University of Tsukuba)",
"テオ・ムザール（フランス）":"Théo Muzar (France)",
"ヘンリエッテ・サブロー・エベセン（デンマーク）":"Henriette Sabroe Ebbesen (Denmark)",
"スティーブン・ギル":"Stephen Gill",
"小原一真":"Kazuma Obara",
"野々上聡人（岡本太郎現代芸術賞大賞受賞）":"Akito Nonoue (Taro Okamoto Award for Contemporary Art Grand Prize winner)",
"松島誠":"Makoto Matsushima",
"エリオット・ヘイグ＋澤田奈々（デュオ）":"Elliot Haigh + Nana Sawada (duo)",
"カシア・クヤブスカ・マーフィー（ポーランド）":"Kasia Kujawska-Murphy (Poland)",
"大崎緑":"Midori Osaki",
"ティアゴ・ロドリゲス（アビニョン演劇祭ディレクター）":"Tiago Rodrigues (Director, Festival d'Avignon)",
"アリス・リポル":"Alice Ripoll",
"梅田哲也":"Tetsuya Umeda",
"ポール・アンドリュー（フランス）":"Paul Andreu (France)",
"アピチャッポン・ウィーラセタクン":"Apichatpong Weerasethakul",
"一柳慧":"Toshi Ichiyanagi",
"ヘアート・ムル（オランダ）":"Geert Mul (Netherlands)",
"妹島和世":"Kazuyo Sejima",
"坂本龍一＋高谷史郎":"Ryuichi Sakamoto + Shiro Takatani",
"蜷川実花 with EiM":"Mika Ninagawa with EiM",
"山本基（塩のインスタレーション）":"Motoi Yamamoto (salt installations)",
"康夏奈":"Kana Ko",
"久保寛子":"Hiroko Kubo",
"田中千智":"Chisato Tanaka",
"牧野永美子":"Emiko Makino",
"野村仁衣那":"Niina Nomura",
"森正彦（自転車廃材の立体造形）":"Masahiko Mori (sculpture made from discarded bicycle parts)",
"towa-towa":"towa-towa",
"千田泰広":"Yasuhiro Chida",
"開発好明":"Yoshiaki Kaihatsu",
"篠田守男":"Morio Shinoda",
}
